import pygame as pg

# render
VERTICAL_TILES = 14
TILE_SIZE = 64

# window
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = TILE_SIZE * VERTICAL_TILES
SCREEN_SCROLL_THRESHOLD = SCREEN_WIDTH // 4

# animation
DEFAULT_ANIMATION_SPEED = 0.2

# controls
KEY_QUIT = pg.K_ESCAPE
KEY_LEFT = pg.K_a
KEY_RIGHT = pg.K_d
KEY_JUMP = pg.K_SPACE
KEY_SPRINT = pg.K_w
KEY_SNEAK = pg.K_s

# player behavior
DEFAULT_PLAYER_WALK_MULTIPLIER = 1
DEFAULT_PLAYER_SNEAK_MULTIPLIER = 0.625
DEFAULT_PLAYER_SPRINT_MULTIPLIER = 1.5
DEFAULT_PLAYER_MAX_MOMENTUM = 8
DEFAULT_PLAYER_INERTIA = DEFAULT_PLAYER_MAX_MOMENTUM/10
DEFAULT_PLAYER_JUMP_COOLDOWN = 5
DEFAULT_PLAYER_MAX_JUMPS = 2
DEFAULT_PLAYER_JUMP_SPEED = -20
DEFAULT_PLAYER_GRAVITY = 0.75
DEFAULT_PLAYER_TERMINAL_VELOCITY = 10